### PR TITLE
feat(dependency): phpunit 7.x

### PR DESCRIPTION
**Pull request by Gounlaf**
upgrade package phpunit to branch 7.x

### CODE REVIEW

**Comment by natebrunette** [comment]
Thanks 👍

**Comment by natebrunette** [comment]
Needs `composer update` to ensure compatibility.

**Comment by Gounlaf** [comment]
You meed you need the lockfile ? I've updated and run unit tests locally.

**Comment by natebrunette** [comment]
Yeah, we need a lockfile update, otherwise sensiolabs insights will complain.

**Comment by natebrunette** [comment]
If you want to roll both PRs into one, that's ok with me.

**Comment by Gounlaf** [comment]
> Yeah, we need a lockfile update, otherwise sensiolabs insights will complain.

Okay.

> If you want to roll both PRs into one, that's ok with me.

Nah. Merge one first and I will rebase the second one ;)

Edit: php-parser first if possible ^^

**Pull request merged**
